### ISSUE TITLE
#reproducible-builds and "diffoscope" package

### ISSUE THREAD

**Issue by lamby** [sebastinas/debian-devel-changes-bot#6]
Please could you make the BTS bot spam `#reproducible-builds` with details for the `diffoscope` package? It already emits to `#debian-reproducible` (and we want to keep those).

**Comment by sebastinas** [comment]
FWIW, #debian-reproducible currently gets notifications based on the maintainer address (reproducible-builds@lists.alioth.debian.org). This address will need an update sooner or later.
